cluster.name: CLUSTER_NAME
bootstrap.memory_lock: true
index.auto_expand_replicas: 0-all
network.publish_host: _ec2:publicIpv4_
discovery.zen.hosts_provider: ec2
cloud.node.auto_attributes: true
http.max_initial_line_length: 16kb
indices.query.bool.max_clause_count: 10000
